### ISSUE TITLE
xcode8 don't work ?

### ISSUE THREAD

**Issue by YongbaoWang** [yinanwang1/XcodeTemplate#1]
xcode8, your template don't work,can you tell me,where is wrong  ? thanks

**Comment by yinanwang1** [comment]
Xcode8 测试是可以用的。你再看下文章中细节。

**Comment by lhkzhl** [comment]
把文件copy到指定目录之后 ，最后一步，新建不出来文件，不知道为什么

**Comment by yinanwang1** [comment]
是不是修改了ViewController的名字，这个名字修改需要将所有的地方都要修改。

**Comment by snake406635029** [comment]
最后一步，新建不出来，xcode9， 什么都没有修改，就把你的文件放到Source下了

**Comment by yinanwang1** [comment]
我在Xcode8 和 Xcode9中都试了是可以用的。  最后一步新建是指在Demo工程中进行New File是吧，那么这个时候需要SubClass of:  一定要填写 BaseViewController 的。  
这个BaseViewController是你在BaseVC.xctemplate中定义好的。
